package com.skgtecnologia.sisem.domain.medicalhistory.model

const val INITIAL_VITAL_SIGNS = "INITIAL_VITAL_SIGNS"
const val DURING_VITAL_SIGNS = "DURING_VITAL_SIGNS"
const val END_VITAL_SIGNS = "END_VITAL_SIGNS"

const val GLASGOW_MRO_KEY = "KEY_GLASGOW_SCALE_MRO"
const val GLASGOW_MRV_KEY = "KEY_GLASGOW_SCALE_MRV"
const val GLASGOW_MRM_KEY = "KEY_GLASGOW_SCALE_MRM"
const val GLASGOW_TOTAL_KEY = "GLASGOW_TOTAL_VALUE"
const val GLASGOW_RTS_KEY = "GLASGOW_RTS"

const val TAS_KEY = "TAS"
const val FC_KEY = "FC"
const val TEMPERATURE_KEY = "Temperatura"
const val GLUCOMETRY_KEY = "Glucometria"

const val FUR_KEY = "KEY_GYNECOBSTETRICS_FUR"
const val PREGNANT_FUR_KEY = "PREGNANT_FUR"
const val PREGNANT_WEEKS_KEY = "PREGNANT_WEEKS"

const val ALIVE_KEY = "KEY_ALIVE"

const val ACCEPT_TRANSFER_KEY = "KEY_ACCEPT_TRANSFER"

const val FIRST_NAME_KEY = "KEY_NAME"
const val SECOND_NAME_KEY = "KEY_SECOND_NAME"
const val LASTNAME_KEY = "KEY_LASTNAME"
const val SECOND_LASTNAME_KEY = "KEY_SECOND_LASTNAME"
const val DOCUMENT_KEY = "KEY_DOCUMENT"
const val AUTH_NAME_KEY = "KEY_SECTION_PROC_AUTH_NAME"
const val RESPONSIBLE_NAME_KEY = "KEY_COMPLETE_NAME_RESPONSIBLE"
const val RESPONSIBLE_DOCUMENT_TYPE_KEY = "KEY_DOCUMENT_TYPE_RESPONSIBLE"
const val RESPONSIBLE_DOCUMENT_NUMBER_KEY = "KEY_DOCUMENT_RESPONSIBLE"
const val WITHDRAWAL_RESPONSIBLE_KEY = "KEY_WITHDRAWAL_COMPANION_RICH"

// region WITHDRAWAL
const val HEADER_WITHDRAWAL_KEY = "KEY_HEADER_WITHDRAWAL"
const val WITHDRAWAL_TYPE_KEY = "KEY_WITHDRAWAL_TYPE"
const val WITHDRAWAL_EXTRA_INFO_KEY = "KEY_WITHDRAWAL_EXTRA_INFO"
const val WITHDRAWAL_STATEMENT_KEY = "WITHDRAWAL_STATEMENT"
const val WHO_WITHDRAWAL_RESPONSIBLE_KEY = "KEY_WHO_WITHDRAWAL_RESPONSIBLE"
const val WITHDRAWAL_REPONSIBLE_NAME_KEY = "KEY_WITHDRAWAL_REPONSIBLE_NAME"
const val DOCUMENT_TYPE_W_KEY = "KEY_DOCUMENT_TYPE_W"
const val DOCUMENT_W_KEY = "KEY_DOCUMENT_W"
const val PLACE_DOCUMENT_RESPONSIBLE_W_KEY = "KEY_PLACE_DOCUMENT_RESPONSIBLE_W"
const val RELATIONSHIIP_W_KEY = "KEY_RELATIONSHIIP_W"
const val WITHDRAWAL_COMPANION_RICH_KEY = "KEY_WITHDRAWAL_COMPANION_RICH"
const val PLACE_DOCUMENT_COMPANION_W_KEY = "KEY_PLACE_DOCUMENT_COMPANION_W"
const val WITHDRAWAL_DECLARATION_KEY = "KEY_WITHDRAWAL_DECLARATION"
const val WITHDRAWAL_CAUSES_KEY = "KEY_WITHDRAWAL_CAUSES"
const val WITHDRAWAL_CONSTANCY_KEY = "KEY_WITHDRAWAL_CONSTANCY"
const val SIGN_PERSON_CHARGE_W_KEY = "KEY_SIGN_PERSON_CHARGE_W"
const val WITHDRAWAL_EXTRA_INFO_2_KEY = "KEY_WITHDRAWAL_EXTRA_INFO_2"
const val WITHDRAWAL_REPONSIBLE_REFUSE_SIGN_KEY = "KEY_WITHDRAWAL_REPONSIBLE_REFUSE_SIGN"
// endregion

// FIXME: Move this to String resources
const val APPLIED_DOSES = "Dosis aplicada"
const val CODE = "Código"
const val QUANTITY_USED = "Cantidad utilizada"
const val ADMINISTRATION_ROUTE = "Via de administración"
