package com.skgtecnologia.sisem.domain.report.model

enum class AddReportIdentifier {
    ADD_REPORT_CANCEL_BANNER,
    ADD_REPORT_CONTINUE_BANNER,
    ADD_REPORT_ENTRY_CANCEL_BUTTON,
    ADD_REPORT_ENTRY_DESCRIPTION,
    ADD_REPORT_ENTRY_TOPIC,
    SEND_REPORT_ENTRY_SEND_BUTTON
}
