package com.skgtecnologia.sisem.domain.model.body

enum class BodyRowType {
    BUTTON,
    CHIP,
    CHIP_OPTIONS,
    CHIP_SELECTION,
    DETAILED_INFO_LIST,
    DROP_DOWN,
    FILTERS,
    FINDING,
    FINGERPRINT,
    FOOTER,
    HEADER,
    HUMAN_BODY,
    IMAGE_BUTTON,
    IMAGE_BUTTON_SECTION,
    INFO_CARD,
    INVENTORY_CHECK,
    LABEL,
    PASSWORD_TEXT_FIELD,
    RICH_LABEL,
    SEGMENTED_SWITCH,
    SLIDER,
    STEPPER,
    TERMS_AND_CONDITIONS,
    TEXT_FIELD
}
